import { StyleSheet } from 'react-native';
// レスポンシブ対応
import {widthPercentageToDP as wp, heightPercentageToDP as hp} from 'react-native-responsive-screen';
import {RFPercentage} from "react-native-responsive-fontsize";

export default StyleSheet.create({
    contents_a: {
        height: '6%',
        backgroundColor: '#f0f6da',
        borderColor:'gray',
        borderTopWidth: 0.5,
        borderRightWidth: 0.5,
        borderLeftWidth: 0.5,
    },
    contents_b: {
        height: '6%',
        backgroundColor: '#f0f6da',
        borderColor:'gray',
        borderRightWidth: 0.5,
        borderLeftWidth: 0.5,
    },
    contents_c: {
        height: '9%',
        backgroundColor: '#f0f6da',
        borderColor:'gray',
        borderRightWidth: 0.5,
        borderLeftWidth: 0.5,
    },
    contents_d: {
        height: '38%',
        backgroundColor: '#f0f6da',
        borderColor:'gray',
        borderRightWidth: 0.5,
        borderLeftWidth: 0.5,
        borderBottomWidth: 0.5,
        alignItems: 'flex-start',
    },
    contents_e: {
        height: '68%',
        backgroundColor: '#f0f6da',
        borderColor:'gray',
        borderRightWidth: 0.5,
        borderLeftWidth: 0.5,
        borderBottomWidth: 0.5,
        alignItems: 'flex-start',
    },
    contents_f: {
        height: '74%',
        backgroundColor: '#f0f6da',
        borderColor:'gray',
        borderRightWidth: 0.5,
        borderLeftWidth: 0.5,
        borderBottomWidth: 0.5,
        alignItems: 'flex-start',
    },
    contents_g: {
        height: '62%',
        backgroundColor: '#f0f6da',
        borderColor:'gray',
        borderRightWidth: 0.5,
        borderLeftWidth: 0.5,
        borderBottomWidth: 0.5,
        alignItems: 'flex-start',
    },

    labelText_custom: {
        fontSize: RFPercentage(1.8),
        width: wp(16),
        marginLeft: 5,
        marginRight: 5,
        marginTop: 5,
        marginBottom: 5,
        paddingLeft: 5,
        paddingRight: 5,
        paddingTop: 5,
        paddingBottom: 5,
    },
    labelText_custom_term: {
        fontSize: RFPercentage(1.8),
        marginLeft: 7,
        marginRight: 7,
        marginTop: 7,
        marginBottom: 7,
        paddingLeft: 7,
        paddingRight: 7,
        paddingTop: 7,
        paddingBottom: 7,
    },
    errorText_custom: {
        fontSize: RFPercentage(1.8),
        marginLeft: 5,
        marginRight: 5,
        marginTop: 5,
        marginBottom: 5,
        paddingLeft: 5,
        paddingRight: 5,
        paddingTop: 5,
        paddingBottom: 5,
    },
    input_custom: {
        fontSize: RFPercentage(1.8),
        width: wp(40),
        marginLeft: 5,
        marginRight: 5,
        marginTop: 5,
        marginBottom: 5,
        alignItems: 'flex-start',
    },
    input_custom_date: {
        fontSize: RFPercentage(1.8),
        width: wp(14.5),
        marginLeft: 5,
        marginRight: 5,
        marginTop: 5,
        marginBottom: 5,
        alignItems: 'flex-start',
    },
    dropdown_custom: {
        width: wp(7),
        padding: 0,
    },
    dropdown_text_custom: {
        marginLeft: 5,
        marginRight: 5,
        marginTop: 5,
        marginBottom: 5,
    },
    dropdown_dropdown_custom: {
        width: wp(7),
        height: hp(60),
    },
    defaultTextStyle_custom: {
        color: '#000000',
    },

});